export { Hero } from './Hero'
export { Features } from './Features'
export { ComingSoon } from './ComingSoon'
export { HowItWorks } from './HowItWorks'
export { About } from './About'
export { EmailCapture } from './EmailCapture'
